name: Lint source code

on:
  pull_request:
    branches:
      - develop

jobs:
  lint:
    name: Lint source code
    runs-on: ubuntu-latest
    steps:
      - name: Check out the source repository
        uses: actions/checkout@v3.0.0

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.0.0

      - name: Install dependencies
        run: npm ci

      - name: Lint the source
        run: npm run lint
